name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Test Build
        run: make build
  docs:
    name: Build Documentation
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install virtualenv
        run: sudo pip3 install virtualenv
      - name: Build documentation
        run: |
          export PATH=/usr/local/bin:$PATH
          ./docs/build.sh -r development -v development
